name: 'cleanblazor'
version: '3.4'

services:
  cleanblazor:
    build:
      context: .
      dockerfile: src/Server/Dockerfile
    environment:
      - "ConnectionStrings__DefaultConnection=Server=localhost,1433;Database=CleanBlazor;User=sa;Password=3Hg3QF2dQWoaeT;TrustServerCertificate=True;"
      - "ASPNETCORE_Kestrel__Certificates__Default__Password=securePassword123"
      - "ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx"
    volumes:
      - ~/.aspnet/https:/https:ro
    ports:
      - "5005:5005"
      - "5006:5006"
    depends_on:
      - db
    restart: no
    container_name: cleanblazor
    profiles:
      - donotstart
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      - "MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}"
      - "ACCEPT_EULA=Y"
    ports:
        - "1433:1433"
        - "1933:1933"
    container_name: mssql
